### PR TITLE
Added T-s value pair for definition of fluid states

### PR DESCRIPTION
**Pull request by spinnau**
Included (T,s) value pairs for instantiation of Props and State classes as discussed in #117 and #118.
- The new value pair was also added to the consistency test: `test_subcrit_twophase_consistency()` works for (T,s) pairs with all fluids
- Updated API doc

### CODE REVIEW

**Comment by ibell** [comment]
That looks great! 

Can you please make a figure like the one at the bottom of http://coolprop.sourceforge.net/Fluids/Water.html with T-s coordinates just to put my mind at ease?  If it looks good, I'll pull.

**Comment by spinnau** [comment]
That was a good idea. I have tested before with some T,s value pairs for all phase regions with different fluids without any problems. But at creating of the T-s-diagram with a lot of input values some calculations went wrong, as the used Secant solver got negative solutions for the density. Thus, I thought on a constrained solver and thanks to your work, there was already one available :-)

With the BoundedSecant solver it works fine now. For some fluids like D5 their are deviations between `rho(T-s)` and `s(T,rho)` solutions for very high and very low pressures. The
`test_subcrit_twophase_consistency()` also ran OK for (T,s) pairs with all fluids.

water

propane

d5

``` python
from CoolProp.Plots.Plots import Ph,Ps,Ts
from CoolProp.CoolProp import Props
from matplotlib import pyplot as plt
import numpy as np

Ref = "Water"
fig = plt.figure(figsize=(15,5))
ax1 = fig.add_subplot(131)
ax2 = fig.add_subplot(132)
ax3 = fig.add_subplot(133)

Tmin = Props(Ref,'Tmin')+3
Tmax = Props(Ref,'Tcrit')*1.5
pmin = Props('P','T',Tmin,'Q',0,Ref)
pmax = Props(Ref,'pcrit')*2
hmin = Props('H','T',Tmin,'Q',0,Ref)
hmax = 2*Props('H','T',Props(Ref,'Tcrit')-1,'Q',1,Ref)-hmin
smin = Props('S','T',Tmin,'Q',0,Ref)
smax = 2*Props('S','T',Props(Ref,'Tcrit')-1,'Q',1,Ref)-smin

Ph(Ref, axis = ax1, Tmin = Tmin, Tmax = Props(Ref,'Tcrit'))
Ps(Ref, axis = ax2, Tmin = Tmin, Tmax = Props(Ref,'Tcrit'))
Ts(Ref, axis = ax3, Tmin = Tmin)

for p in np.linspace(pmin,pmax,10):
    for h in np.linspace(hmin,hmax):
        _bad = False
        try:
            T = Props('T','H',h,'P',p,Ref)
            rho = Props('D','H',h,'P',p,Ref)
            hEOS = Props('H','T',T,'D',rho,Ref)
        except ValueError:
            _bad = True
        if _bad or abs(hEOS/h-1)>1e-6:
            ax1.plot(h,p,'x',ms = 10)
        else:
            ax1.plot(h,p,'k.', ms = 1)

for p in np.linspace(pmin,pmax,10):
    for s in np.linspace(smin,smax):
        _bad = False
        try:
            T = Props('T','S',s,'P',p,Ref)
            rho = Props('D','S',s,'P',p,Ref)
            sEOS = Props('S','T',T,'D',rho,Ref)
        except ValueError:
            _bad = True
            print T, p, s
        if _bad or abs(sEOS/s-1)>1e-6:
            ax2.plot(s,p,'x',ms = 10)
        else:
            ax2.plot(s,p,'k.', ms = 1)

for _T in np.linspace(Tmin,Tmax,10):
    for s in np.linspace(smin,smax):
        _bad = False        
        try:
            T = Props('T','T',_T,'S',s,Ref)       
            rho = Props('D','T',_T,'S',s,Ref)
            sEOS = Props('S','T',T,'D',rho,Ref)
        except ValueError:
            _bad = True
        if _bad or abs(sEOS/s-1)>1e-6:
            ax3.plot(s,_T,'x',ms = 10)
        else:
            ax3.plot(s,_T,'k.', ms = 1)


plt.tight_layout()
plt.savefig('{0}.png'.format(Ref))
plt.show()
```

**Comment by ibell** [comment]
Great, make the changes to the pull request and I'll pull it.  Thanks for
all your help!!

**Comment by spinnau** [comment]
The change from the Secant solver to BoundedSecant was already commited to this PR. Do you have other things in mind, like adding the T-s-diagramm code to _Web/FluidInfoGenerator.py_?

**Comment by ibell** [comment]
Can you freshen this PR so that we can auto-merge it?  If you wanted to add the T-S solver to the docs, perhaps that would be best to hold off for another PR?

**Comment by spinnau** [comment]
I have rebased the commits on coolprop/master branch...

**Pull request merged**
